### ISSUE TITLE
Not really an Issue

### ISSUE THREAD

**Issue by genesisemmloh** [Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo#10]
**Describe the bug**
Its in Fact a Question:
i have implemented this but in TypeScript and when implementing a component i connect this to the auth hook... state.. and then i see on my component repeated info. the state from the auth hook and same time the properties passed from the WrappedComponent.

... Is the Auth reducer really necesary? isAuthenticated property could also be passed on the WrappedComponent or not?

I did not Find a way to contact you sorry for the Issue...
thanks for your project it helped me to start on MSAL with React :)

**Comment by derisen** [comment]
@genesisemmloh you're welcome : ) `isAuthenticated ` is simply a flag to keep track of the app's state and show the appropriate UI elements. It's part of the `auth` reducer since the sample demonstrates React & Redux pattern. But of course you can keep track of this in other ways (for instance, as a state in 'authProvider' HOC).

Not sure I understand your question here -do you want to avoid using Redux in general? Can you elaborate on some code snippet?

**Comment by genesisemmloh** [comment]
I'm not a Pro in react, your example helped me thanks.  but the fact that the authprovide is a hoc, wrapping the complete app means will be on all the components passed as properties, and perhaps it doesn't need to have a reducer or what was the intention?

**Comment by derisen** [comment]
I see. The sample was aiming to show how to use MSAL.js together with Redux and HOC patterns in a React application. There's no hard requirement here, you can certainly avoid using Redux at all (if you are wondering why use Redux in general, you can see their [documentaiton](https://redux.js.org/introduction/motivation)). 

If you would like to see an MSAL.js & React sample using only the HOC pattern please take a [look at here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-core-samples/react-sample-app).

**Comment by mohsinonxrm** [comment]
@genesisemmloh , can you share the typescript based implementation?

@derisen , do you plan to release typescript version of this sample?

**Comment by mohsinonxrm** [comment]
@derisen , I also saw some breaking changes in beta.4 vs beta.2, so the sample will need to be updated.

**Comment by derisen** [comment]
@mohsinonxrm a typescript based sample would be a good idea, thank you for the suggestion. Unlikely for this particular sample but we will consider releasing a typescript sample.

Regarding beta.4 update -thank you for the heads up, will be done asap

**Comment by derisen** [comment]
@mohsinonxrm see this for a [typescript sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/TypescriptTestApp2.0)

**Comment by derisen** [comment]
Closing this as no further action to take.
