### ISSUE TITLE
API Exception on PostProfileItem graphID substraction

### ISSUE THREAD

**Issue by YohanSciubukgian** [Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo#14]
**Describe the bug**
the following code is raising an exception: 
```
// OID is represented in id_token as a 32 digit number, while in MS Graph API, the
// preceeding 0s are omitted. The following operation adds the omitted 0s back.
int x = 32 - profile.Id.Length;
string graphID = new string('0', x) + profile.Id;
```

**To Reproduce**
I have tested the sample with Azure Active Directory set properly for API & SPA.
After being logged in, I clicked on the button Accepted on the SPA :
![image](https://user-images.githubusercontent.com/30290851/89557078-9049fb80-d812-11ea-8deb-c07c29534144.png)
The PostProfileItem endpoint has been reached & profile.Id is filled with a GUID ("00000000-0000-0000-0000-000000000000").
var x = -4 which is not supported by the method `new string('0', x)`

**Expected behavior**
Not raise any exception on this subtraction

**Comment by derisen** [comment]
@YohanSciubukgian thank you for catching this. I've opened a PR -feel free to add yourself as a reviewer.
