### ISSUE TITLE
Not seeing my profile on second login

### ISSUE THREAD

**Issue by dfibuch** [Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo#20]
## Library

- [x] `@azure/msal-browser@2.0.1`

## Description
The sample documentation says:

`Submit your changes. When you sign-in next time, the application will recognize you and show you the profile associated with your Id in the database.`

However, when I login the second time I get the `Accept` button again and clicking it throws a 500 from the backend because it's trying to create the user again.

## Error Message
System.ArgumentException: An item with the same key has already been added.

## Reproduction steps
- Follow the steps to create your profile in the system
- Refresh the page and Login again

**Comment by derisen** [comment]
@dfibuch a regression from the last PR was causing this, it should be gone now. Could you please pull the changes and try again?

**Comment by dfibuch** [comment]
Don't seem to be getting the same error this time, but it is not finding the profile. When I debug the backend, I can see that the `id` being passed in is just one long string, e.g.: `AABBCCDDEEFFGGHH` but when I look in the `ProfileItems` repo the stored object has an `Id` in `Guid` format, e.g.: `AABBCC-DDEE-FFGGHH...` so it will never find it.

It is in `ProfileContainer.jsx` on line 32 where the `oid` has the hyphens removed for some reason. If I stop them from being removed the profile shows up correctly.

I'm happy to do a PR if you want, but need clarification on what the `Id` in the database needs to look like, with hyphens or not?

**Comment by derisen** [comment]
@dfibuch This is interesting. Normally the `oid` is a GUID represented by a 32 digit string in the id token. However the `id` property (which corresponds to `oid`) returned for **Personal Microsoft accounts** are represented without the 0s and dashes. Like:

- Graph Profile `id`: x271a84399aaa7f1
- id token `oid` claim: 00000000-0000-0000-x271-a84399aaa7f1

So we use the following logic to check if they match. In ProfileController.cs:

```csharp
                    string graphID;

                    // OID is represented in id_token as a 32 digit number, while in MS Graph API, the
                    // preceding 0s are sometimes omitted. The following operation adds the omitted 0s back.
                    
                    if (profile.Id.Length < 32) {
                        int x = 32 - profile.Id.Length;
                        graphID = new string('0', x) + profile.Id;
                    } else {
                        graphID = profile.Id;
                    }
```

and in ProfileContainer.jsx we query the mock database with `oid` from id token:

```javascript
                    // Our mock database assign user Ids based on MS Graph API account id, which corresponds to the "oid" claim in the id_token
                    // visit https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens for more information
                    let tokenOID = this.props.auth.idToken.oid.replace(/-/gi, ''); // removing dashes

                    // check if user already exists
                    try {
                        this.props.getProfile(tokenOID);
                    } catch (err) {
                        console.log(err);
                    }
```

Can you verify that you are using a **personal Microsoft account** and your `oid` from id token and `id` from Graph profile corresponds to this scheme? (you can query Graph [here](https://developer.microsoft.com/en-us/graph/graph-explorer))

**Comment by dfibuch** [comment]
I think you've hit the nail on the head. I failed to mention that I am using this with my companies Azure AD (so B2B). Feels like this will be the issue here.

**Comment by derisen** [comment]
@dfibuch that should be it. Work or school account GUIDs are slightly different than personal accounts -at any rate though, your modification should handle it (now I remembered we covered this in the [ReadmeFiles](https://github.com/Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo/blob/master/ReadmeFiles/howto-common.md)).

**Comment by dfibuch** [comment]
Yes you did, I only realised my mistake when I read it for the 8th or so time 😂 

I have now come across the issue a lot of others are having where MSAL 2.0 doesn't work nicely with Azure B2C due to that CORS problem but I don't really want to use v1.3...so waiting patiently 😁

**Comment by derisen** [comment]
That's right, unfortunately. We'll put out a 2x B2C sample as soon as that issue resolves : )

**Comment by dfibuch** [comment]
I've subscribed to a couple of GitHub issues where this is discussed in hope that the announcement of the fix will be there. Is that the best way to do it or is there another source where I should keep an eye on for the fix?

**Comment by derisen** [comment]
that should work out -[this thread](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1795) is keeping track of it.

**Comment by dfibuch** [comment]
Awesome, already subscribed to it :D Thanks for all your help.

**Comment by derisen** [comment]
you're welcome : )
