### ISSUE TITLE
Using loginRedirect doesn't get handled properly

### ISSUE THREAD

**Issue by dfibuch** [Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo#27]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Originally I used `loginPopup` to login a user if there were no tokens present but I've now moved to using `loginRedirect` and have setup the `handleRedirectPromise` to deal with this. My app calls the `login` part automatically when you hit it, so there is no button to press and what I am finding is the following cycle:

- User goes to app and hits `loginRedirect`
- Browser goes to MS to get token and comes back to the RedirectUrl which is the same app
- User still not authenticated so hits `loginRedirect` again but this throws an error
   - ` BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.`
- Promise from MS is returned and `handleRedirectPromise` is hit, user is authenticated

A colleague of mine is using the older version of `msal-browser 1.3` and has the same scenario but he does not receive this error and he has found that there is code that actually handles this within the script of `msal-browser`.

Am I doing something wrong here or is this a bug? I can easily manage this scenario by setting a `sessionStorage` entry to indicate login in already in progress.

**Comment by derisen** [comment]
@dfibuch apologies for the delay. I've just tested the sample again for redirect flow and reproduced the issue. The Redux store account property is set in `App.js` with props passed from `AuthProvider.js`, however when using redirect, the application state is lost after refresh and as such, the store does not get updated (and so the UI), even though the `sessionStorage` has all the necessary information (this is our mistake here, the sample was designed for popup flow first and redirect added later). I will make a PR soon, but in the meantime, can you review [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/initialization.md#redirect-apis) and this [onPageLoad sample here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/VanillaJSTestApp2.0/app/onPageLoad/auth.js) -it shows how to use `handleRedirectPromise()` in your scenario.

**Comment by dfibuch** [comment]
@derisen Thanks for your response and no worries about time, I was on holiday anyway :)

Good to know this is being addressed and was a bug. I have pretty much done what those docs say with my setup, I have this being called in the `constructor` of my `authProvider` 

![image](https://user-images.githubusercontent.com/4235431/92094670-9e1c7d80-edcc-11ea-932c-8ffa22268806.png)

**Comment by derisen** [comment]
That looks about right! In the sample we end up using life cycle methods since auth happens upon button click unlike your case.
