### ISSUE TITLE
Token audience is set to Microsoft Graph, API refuses to accept it

### ISSUE THREAD

**Issue by alexeybogusevich** [Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo#33]
Hi! 
I followed the example and everything was just fine, but then I tried to implement the same approach in my existing application and got the following error: `Bearer error="invalid_token", error_description="The signature is invalid"`. This is caused by the fact that the access token I get from AzureAD is intended for Microsoft Graph and not for my application (its headers are ["aud": "00000003-0000-0000-c000-000000000000",
  "iss": "https://sts.windows.net/5bb4edc8-7c6e-4911-97b0-06a9ef95dd6a/"], whereas the ones I get when following the example are ["aud": "3ef2f30b-0668-4aa1-868c-70b61e786299",
  "iss": "https://login.microsoftonline.com/5bb4edc8-7c6e-4911-97b0-06a9ef95dd6a/v2.0"]). 
The only difference I've made to the readme configuration was concerned with redirectUri (set to "https://localhost:44307/") and resourceUri (set to "http://localhost:5001/api/profile").
Could this be a reason for such a behavior? If not then what am I doing wrong?
Thanks in advance!
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`

## Description

Please provide your question here, including as much relevant details as possible.

Examples:
> "How do I use MSAL with Vue.js"
> "How do I SSO between tabs?"
> "How do I use MSAL to protect my custom Web API?"
> "How can my app support multiple AAD tenants?"
> "When will my scenario be supported?"
> "When will this framework be supported"

**Comment by derisen** [comment]
@alexeybogusevich can you confirm that:

1) when you register your **front-end** app on Azure Portal, you added API permission for 'access_as_user'

![sdf](https://user-images.githubusercontent.com/13197548/94729741-fc2e7900-0316-11eb-8529-e4674200f4e6.png)

2)  ProfileSPA/src/utils/authConfig.js is configured as:

```javascript
export const loginRequest = {
    scopes: ["openid", "profile", "offline_access"]
}

// Add here scopes for access token to be used at the API endpoints.
export const tokenRequest = {
    scopes: [api://{client_id_of_API}/.default]
}
```

If you confirm, then it would be best to send me a network trace (you can use [Fiddler](https://www.telerik.com/fiddler) for that). You can find my email on my profile.

**Comment by alexeybogusevich** [comment]
@derisen, Yes, I do, absolutely. 
![image](https://user-images.githubusercontent.com/35065739/94730344-bf40a180-036b-11eb-9a07-d2ceea4a0c54.png)
![image](https://user-images.githubusercontent.com/35065739/94730591-1fcfde80-036c-11eb-9fd5-492364623f8e.png)

**Comment by derisen** [comment]
@alexeybogusevich in that case please send me a network trace (you can use [Fiddler ](https://www.telerik.com/fiddler)for that). You can find my email on my profile.

**Comment by alexeybogusevich** [comment]
@derisen, okay, thank you! Did it.

**Comment by derisen** [comment]
This issue has been resolved over email correspondence. Closing now.
