### ISSUE TITLE
Missing Directory.AccessAsUser.All permission?

### ISSUE THREAD

**Issue by gsandorx** [Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo#37]
I have followed this guide and others showcasing the same scenario. I kept getting the "Insufficient privileges to complete the operation" error when calling `var profile = await _graphServiceClient.Me.Request().GetAsync();`.

I added extra permission (Directory.AccessAsUser.All) in my API registration section in Azure AD and I got it working. I didn't touch anything else. 

Is this permission missing from the readme file in this repo, in particular in STEP 4 > ProfileAPI > item 6? 

## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`

## Description

Please provide your question here, including as much relevant details as possible.

Examples:
> "How do I use MSAL with Vue.js"
> "How do I SSO between tabs?"
> "How do I use MSAL to protect my custom Web API?"
> "How can my app support multiple AAD tenants?"
> "When will my scenario be supported?"
> "When will this framework be supported"

**Comment by derisen** [comment]
@gsandorx for only accessing the signed-in user's profile on Graph API,  `Directory.AccessAsUser.All` shouldn't be needed, as this is a higher privilege permission requiring admin consent. I'd like to know why the error occurs when calling the `Me` endpoint. Let me try to reproduce this on my end and I'll get back to you.

**Comment by gsandorx** [comment]
Hi @derisen  any luck?

**Comment by derisen** [comment]
@gsandorx I wasn't able to reproduce this. What I'm suspecting is that, a glitch happens during account selection screen and somehow the application tries to query the Graph API for some user other than the one that has signed-in to the application, which would result in "insufficient privilege" error... 

Can you send me a network trace, using something like [Fiddler](https://www.telerik.com/fiddler)? You can find my email on my [profile](https://github.com/derisen).

I'm also working on updating the sample and improving some aspects, which might prevent this.

**Comment by gsandorx** [comment]
Hi, I think I found the issue: I was using a "guest" account and Azure AD has different permission requirements for those accounts. You did help me though: I didn't know about "Fiddler" and that did the trick in getting to the root cause :D

**Comment by derisen** [comment]
Awesome! That sounds like it. 

Closing this then. Let us know if you need anything else.
