### ISSUE TITLE
Add a scope

### ISSUE THREAD

**Issue by senal** [Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo#42]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `@azure/msal-browser@2.13.1`
- [ ] `@azure/msal-react@1.0.0-beta.1`

## Description
When adding scope it is requred (mandatory fields) to provide:
**Admin consent display name:**
**Admin consent description:**

![image](https://user-images.githubusercontent.com/2841066/113978369-3741d400-9887-11eb-8057-44313f3f69c0.png)

But in the document it says we require to provide only the **user consent** fields.
Since it's mandatory, should we provide values to the above fields.

Please advise.

**Comment by derisen** [comment]
@senal thanks for catching this. Yes, please fill-in those fields as well. I'll update the README asap.

**Comment by derisen** [comment]
README updated

**Comment by derisen** [comment]
Closing as resolved.
