### ISSUE TITLE
Calling a downstrem web api with OBO flow

### ISSUE THREAD

**Issue by senal** [Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo#44]
## Library

- [ ] `@azure/msal-browser@2.13.1`
- [ ] `@azure/msal-react@1.0.0-beta.1`

## Description
scenario:
I have 2 applications. They are structured as follows

**App1**
- tra-spa-dev
- tra-api-dev

**App2**
- mr-spa-dev
- mr-api-dev

I have registered SPA and API applications in the Azure portal as stated in this tutorial.
With a successfully logged in user, the SPA application can access secured endpoints of the respective API.

Now I need to access  "**mr-api-dev**" from "**tra-api-dev**", basically I need to access the down streem API.
So I added, **mr-api-dev** in to the API permissions list of **tra-api-dev**

![image](https://user-images.githubusercontent.com/2841066/118229678-c3bb6400-b4cf-11eb-9d24-0b358e920a3d.png)

I have added the following configuration in the **tra-api-dev** startup.cs class

`

     services.AddMicrosoftIdentityWebApiAuthentication(Configuration)
                .EnableTokenAcquisitionToCallDownstreamApi()
                .AddDownstreamWebApi("mr", o => {
                    o.BaseUrl = "http://localhost:5010/graphql";
                    o.Scopes = "access_as_user";
                })
                .AddInMemoryTokenCaches();

`

AzureAD configuration settings are as follows:

`

    AzureAd": {
       "Domain": "msaltestingjs.onmicrosoft.com",
       "ClientId": "api-clientid",
       "ClientSecret": "secret",
       "Instance": "https://login.microsoftonline.com/",
       "TenantId": "tenant-id"
    }

`

From my "**tra-api-dev**" service class, I called the "**mr-api-dev**" API as follows:

**Please note that I'm using GraphQLClient, hence I need to get a token explicitly to be added as a bearer token in the header. 
So I used, ITokenAcquisition implementation to obtain a valid token.**

`

    var scopesToAccessDownstreamApi = new string[] { "api://[tra-api-dev application id]/access_as_user" };
    var token = await _tokenAcquisition.GetAccessTokenForUserAsync(scopesToAccessDownstreamApi);
    var query = MasterRecordQueries.FilterMasterRecords(filter);
    _graphQLClient.HttpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {token}");
    var response = await _graphQLClient.SendQueryAsync<FilterMasterRecordResponse>(query);
    return response.Data;

`

However, the request didn't succeed. I get the following error in response headers.

`

    {Date: Fri, 14 May 2021 05:55:05 GMT
    Server: Kestrel
    WWW-Authenticate: Bearer error="invalid_token", error_description="The audience 'api://[tra-api-dev application id]' is invalid"
   }

`

Appreciate it if someone could provide me with an insight into what's wrong with my implementation or configurations.

Please feel free to contact me if you require further information.

**Comment by derisen** [comment]
@senal apologies for late response, I've missed this. From the error response you shared, this looks like a token validation issue. On Azure portal > App registration > web API registration (mr-api-dev) > Manifest, can you set the `accessTokenAcceptedVersion` property to **2** and give this a try again?

**Comment by derisen** [comment]
@senal on second thought, in the code snippet you shared, it looks like you are acquiring a token that is meant for tra-api-dev.

```csharp
var scopesToAccessDownstreamApi = new string[] { "api://[tra-api-dev application id]/access_as_user" };
var token = await _tokenAcquisition.GetAccessTokenForUserAsync(scopesToAccessDownstreamApi);
// ...
```

But you can't use that token to access mr-api-dev, as the audience of the token will be tra-api-dev's clientId, not mr-api-dev's clientId. Is there a public repo where I can look at your code?

**Comment by derisen** [comment]
@senal any updates? Were you able to resolve your issue?

**Comment by senal** [comment]
@derisen ,
Thank you very much for your feedback. 
As you mentioned before, I have mixed up with scopes. Now I sorted out the issues. Thanks.
