### ISSUE TITLE
Cannot get profile information after logging in

### ISSUE THREAD

**Issue by andrewcrayden** [Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo#45]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
azure/msal-browser: "^2.13.1"  
.NET Core 3.1
## Description
1. Cloned this git repository.
2. Followed the steps from readme in Azure AD. 
3. Launched the server and the SPA, and successfully logged in. 
4. Presented with "Welcome Onboard! You will now be asked to update your profile information." and the "Accept" button. Before clicking "Accept", the browser console output the following message:
>GET https://localhost:44351/api/profile/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 404 serviceActions.js:9 

Logging in with a "work" account I believe. This is my M365 business account, with custom domain name. This account was used for the Azure admin/tenant. Not sure if the user id is in a different format. I also invited a personal account as a guest user into the AAD tenant, but same error.

Not sure how to get the user profile information after logging in because of this error.

## Error Message
>GET https://localhost:44351/api/profile/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 404 serviceActions.js:9 

## Security

- [ ] Is this issue security related?

## Regression

- [ ] Did this behavior work before?

Version:

## MSAL Configuration

```js
export const msalConfig = {
    auth: {
        clientId: "[Profile SPA AAD Client ID]",
        authority: "https://login.microsoftonline.com/[AAD Tenant ID]",
        redirectUri: "http://localhost:3000"
    },
    cache: {
        cacheLocation: "localStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: false // Set this to "true" if you are having issues on IE11 or Edge
    },
}
```

## Reproduction steps

Followed the same code in the repo, and steps within the readme.

## Browsers/Environment

- [ ] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by derisen** [comment]
@andrewcrayden the error is totally expected! When you sign-in, the app checks the backend if there is a record for that particular user [oid](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens#payload-claims), and if receives a 404 error, presents you the onboarding screen. Once you hit accept, the backend queries the Microsoft Graph and prepopulates the form with whatever info is available. Once you submit the form, a record for that profile is added to the mock database. Next time you sign-in, the app will recognize you and present the record directly, without showing the onboarding screen.

After you submit the form, do you get the 404 error again next time you sign in?

**Comment by andrewcrayden** [comment]
@derisen After logging in and seeing the first error above, the JS console prints the following errors when clicking `Accept`:
>Failed to load resource: the server responded with a status of 404()
>POST https://localhost:44351/api/profile 400                                                                    serviceActions.js:35
>POST https://localhost:44351/api/profile net::ERR_HTTP2_PROTOCOL_ERROR 400          serviceActions.js:35
>TypeError: Failed to fetch                                                                                                    serviceactions.js:54

![image](https://user-images.githubusercontent.com/5587564/119169268-0a084a00-ba1f-11eb-9783-a17d1c033f3f.png)

**Comment by derisen** [comment]
@andrewcrayden apologies for delay. As you mentioned, it might be related to the particular account that you signed in with. Can we double check that this account has a user profile on Graph? Can you go to the [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer), sing-in with the same account and query `https://graph.microsoft.com/v1.0/me`? Is this working?

![sdf](https://user-images.githubusercontent.com/13197548/119546489-d2fca600-bd48-11eb-8ccb-4e1aa8292d11.png)

**Comment by derisen** [comment]
@andrewcrayden any updates? does the issue persists?

**Comment by derisen** [comment]
Closing, let us know if you need further help
