### ISSUE TITLE
Call a chain of downstream APIs within a one request

### ISSUE THREAD

**Issue by senal** [Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo#46]
Appreciate your clarification with regard to my below question.

Aassume I have a chain of downstream API calls to be made.
e.g 
From client-spa application a request made to access api-A, 
then  api-A calls api-B, api-B needs to call api-C to satisfy api-A request.

How do you configure them in Azure? Any recommended best practice to manage these sort of integrations?

**Comment by derisen** [comment]
@senal no worries : ) For this scenario, I would suggest going through [this tutorial](https://github.com/Azure-Samples/ms-identity-javascript-tutorial/tree/main/4-AdvancedGrants/2-call-api-api-ca) once, as it matches your case. There's stuff there about handling conditional access challenges, but you can ignore that bit.

**Comment by senal** [comment]
close the ticket with thanks @derisen
