### ISSUE TITLE
How to make this app works witn work/school Microsoft accounts?

### ISSUE THREAD

**Issue by greybax** [Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo#7]
Is it possible to make this app works with work/school MS accounts?
Now I'm getting error while trying to auth under my work account:
![image](https://user-images.githubusercontent.com/3235047/84560256-02accc80-acf7-11ea-9400-9a022a40eaa8.png)

**Comment by derisen** [comment]
@greybax please see [this answer](https://github.com/Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo/issues/5#issuecomment-642861934).

**Comment by derisen** [comment]
Closing for now. Let us know if you have more questions.
